### ISSUE TITLE
OpenAsSecondary With Column Families doesn't initlize column families memory

### ISSUE THREAD

**Issue by AllegraMcdonnell123** [curiosity-ai/rocksdb-sharp#17]
Hi just tried to use the new OpenAsSecondary feature and noticed that when you try to open the rocksdb with column families it throws memory couruption exception,
i think this caused because the db instance is initialized with Native.Instance.rocksdb_open_as_secondary and not Native.Instance.rocksdb_open_as_secondary_column_families and thus the column families are not allocated into memory 
@roeeiit1 @theolivenbaum

**Comment by roeeiit1** [comment]
Oh damn,
When I'll get home from work I'll take a look, think it's a real quick fix tho

**Comment by AllegraMcdonnell123** [comment]
Thanks for the quick response! :octocat: 
@theolivenbaum Could you please retrigger the azure build pipeline as i saw that it failed on the merge and thuse no new packages have been created?

**Comment by theolivenbaum** [comment]
I think there's an error in the code - I'll check later today - there was also a new rocksdb release, so good timing for a new package!
