### ISSUE TITLE
No OSS license?

### ISSUE THREAD

**Issue by thedevopsmachine** [curiosity-ai/rocksdb-sharp#29]
Hey team, I was hoping to use this project for something I'm working on, but since it doesn't have an OSS license assigned, I'm not allowed to. Without explicitly assigning a license, we have to treat it as if it has the most restrictive license.

Can you please assign an OSS license to the project? Preferably something open like Apache 2.

Thanks very much

**Comment by dahlia** [comment]
It seems the 2-Clause BSD:

<https://github.com/curiosity-ai/rocksdb-sharp/blob/d131cb7dec4fabeb6809e8dd759aad4be4480596/csharp/RocksDbSharp.csproj#L15>

However, it would be good to have a *COPYING* or *LICENSE* file.

**Comment by thedevopsmachine** [comment]
Thanks!

**Comment by queequac** [comment]
@theolivenbaum The underlying native RocksDB library has a dual-license, where you can choose between GPLv2 and Apache 2.0.

Is there a reason why your nuget-package states BSD-2-Clause?
For simplicity you might consider switching to Apache 2.0, which would ease clearing apps using your packages.

And as @dahlia suggests, please add a LICENSE file to the code base, so GitHub will automatically add the license info to the project infos.

**Comment by theolivenbaum** [comment]
Can't believe I've never noticed this. I'll fix asap!

**Comment by theolivenbaum** [comment]
Fixed by b774336a37d8da75ae1b292ab09fc5acdb5a1c6a
