### ISSUE TITLE
There are some problems on the M1Pro chip of the mac

### ISSUE THREAD

**Issue by mailes** [curiosity-ai/rocksdb-sharp#36]
System.TypeInitializationException: "The type initializer for 'RocksDbSharp.Native' threw an exception." ---> NativeImport.NativeLoadException: "Unable to locate rocksdb native library, either install it, or use RocksDbNative nuget package\nSearched:\n/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/runtimes/osx-arm64/native/librocksdb-7.7.3.dylib: (NativeLoadException) dlopen: dlopen(/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/runtimes/osx-arm64/native/librocksdb-7.7.3.dylib, 0x0002): tried: '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/runtimes/osx-arm64/native/librocksdb-7.7.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/runtimes/osx-arm64/native/librocksdb-7.7.3.dylib' (no such file), '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/runtimes/osx-arm64/native/librocksdb-7.7.3.dylib' (no such file)\n/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/runtimes/osx-arm64/native/librocksdb-7.7.dylib: (NativeLoadException) dlopen: dlopen(/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/runtimes/osx-arm64/native/librocksdb-7.7.dylib, 0x0002): tried: '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/runtimes/osx-arm64/native/librocksdb-7.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/runtimes/osx-arm64/native/librocksdb-7.7.dylib' (no such file), '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/runtimes/osx-arm64/native/librocksdb-7.7.dylib' (no such file)\n/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/runtimes/osx-arm64/native/librocksdb-7.dylib: (NativeLoadException) dlopen: dlopen(/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/runtimes/osx-arm64/native/librocksdb-7.dylib, 0x0002): tried: '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/runtimes/osx-arm64/native/librocksdb-7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/runtimes/osx-arm64/native/librocksdb-7.dylib' (no such file), '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/runtimes/osx-arm64/native/librocksdb-7.dylib' (no such file)\n/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/runtimes/osx-arm64/native/librocksdb.dylib: (NativeLoadException) dlopen: dlopen(/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/runtimes/osx-arm64/native/librocksdb.dylib, 0x0002): tried: '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/runtimes/osx-arm64/native/librocksdb.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/runtimes/osx-arm64/native/librocksdb.dylib' (no such file), '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/runtimes/osx-arm64/native/librocksdb.dylib' (no such file)\n/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/arm64/librocksdb-7.7.3.dylib: (NativeLoadException) dlopen: dlopen(/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/arm64/librocksdb-7.7.3.dylib, 0x0002): tried: '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/arm64/librocksdb-7.7.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/arm64/librocksdb-7.7.3.dylib' (no such file), '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/arm64/librocksdb-7.7.3.dylib' (no such file)\n/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/arm64/librocksdb-7.7.dylib: (NativeLoadException) dlopen: dlopen(/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/arm64/librocksdb-7.7.dylib, 0x0002): tried: '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/arm64/librocksdb-7.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/arm64/librocksdb-7.7.dylib' (no such file), '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/arm64/librocksdb-7.7.dylib' (no such file)\n/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/arm64/librocksdb-7.dylib: (NativeLoadException) dlopen: dlopen(/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/arm64/librocksdb-7.dylib, 0x0002): tried: '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/arm64/librocksdb-7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/arm64/librocksdb-7.dylib' (no such file), '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/arm64/librocksdb-7.dylib' (no such file)\n/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/arm64/librocksdb.dylib: (NativeLoadException) dlopen: dlopen(/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/arm64/librocksdb.dylib, 0x0002): tried: '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/arm64/librocksdb.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/arm64/librocksdb.dylib' (no such file), '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/arm64/librocksdb.dylib' (no such file)\n/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/librocksdb-7.7.3.dylib: (NativeLoadException) dlopen: dlopen(/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/librocksdb-7.7.3.dylib, 0x0002): tried: '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/librocksdb-7.7.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/librocksdb-7.7.3.dylib' (no such file), '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/librocksdb-7.7.3.dylib' (no such file)\n/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/librocksdb-7.7.dylib: (NativeLoadException) dlopen: dlopen(/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/librocksdb-7.7.dylib, 0x0002): tried: '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/librocksdb-7.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/librocksdb-7.7.dylib' (no such file), '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/librocksdb-7.7.dylib' (no such file)\n/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/librocksdb-7.dylib: (NativeLoadException) dlopen: dlopen(/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/librocksdb-7.dylib, 0x0002): tried: '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/librocksdb-7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/librocksdb-7.dylib' (no such file), '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/librocksdb-7.dylib' (no such file)\n/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/librocksdb.dylib: (NativeLoadException) dlopen: dlopen(/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/librocksdb.dylib, 0x0002): tried: '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/librocksdb.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/librocksdb.dylib' (no such file), '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/native/librocksdb.dylib' (no such file)\n/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/arm64/librocksdb-7.7.3.dylib: (NativeLoadException) dlopen: dlopen(/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/arm64/librocksdb-7.7.3.dylib, 0x0002): tried: '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/arm64/librocksdb-7.7.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/arm64/librocksdb-7.7.3.dylib' (no such file), '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/arm64/librocksdb-7.7.3.dylib' (no such file)\n/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/arm64/librocksdb-7.7.dylib: (NativeLoadException) dlopen: dlopen(/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/arm64/librocksdb-7.7.dylib, 0x0002): tried: '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/arm64/librocksdb-7.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/arm64/librocksdb-7.7.dylib' (no such file), '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/arm64/librocksdb-7.7.dylib' (no such file)\n/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/arm64/librocksdb-7.dylib: (NativeLoadException) dlopen: dlopen(/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/arm64/librocksdb-7.dylib, 0x0002): tried: '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/arm64/librocksdb-7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/arm64/librocksdb-7.dylib' (no such file), '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/arm64/librocksdb-7.dylib' (no such file)\n/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/arm64/librocksdb.dylib: (NativeLoadException) dlopen: dlopen(/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/arm64/librocksdb.dylib, 0x0002): tried: '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/arm64/librocksdb.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/arm64/librocksdb.dylib' (no such file), '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/arm64/librocksdb.dylib' (no such file)\n/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/librocksdb-7.7.3.dylib: (NativeLoadException) dlopen: dlopen(/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/librocksdb-7.7.3.dylib, 0x0002): tried: '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/librocksdb-7.7.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/librocksdb-7.7.3.dylib' (no such file), '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/librocksdb-7.7.3.dylib' (no such file)\n/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/librocksdb-7.7.dylib: (NativeLoadException) dlopen: dlopen(/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/librocksdb-7.7.dylib, 0x0002): tried: '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/librocksdb-7.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/librocksdb-7.7.dylib' (no such file), '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/librocksdb-7.7.dylib' (no such file)\n/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/librocksdb-7.dylib: (NativeLoadException) dlopen: dlopen(/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/librocksdb-7.dylib, 0x0002): tried: '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/librocksdb-7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/librocksdb-7.dylib' (no such file), '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/librocksdb-7.dylib' (no such file)\n/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/librocksdb.dylib: (NativeLoadException) dlopen: dlopen(/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/librocksdb.dylib, 0x0002): tried: '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/librocksdb.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/librocksdb.dylib' (no such file), '/Users/mqh/Desktop/Git/Ferrite/Ferrite/bin/Debug/net7.0/librocksdb.dylib' (no such file)\nlibrocksdb-7.7.3.dylib: (NativeLoadException) dlopen: dlopen(librocksdb-7.7.3.dylib, 0x0002): tried: 'librocksdb-7.7.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibrocksdb-7.7.3.dylib' (no such file), '/usr/lib/librocksdb-7.7.3.dylib' (no such file, not in dyld cache), 'librocksdb-7.7.3.dylib' (no such file)\nlibrocksdb-7.7.dylib: (NativeLoadException) dlopen: dlopen(librocksdb-7.7.dylib, 0x0002): tried: 'librocksdb-7.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibrocksdb-7.7.dylib' (no such file), '/usr/lib/librocksdb-7.7.dylib' (no such file, not in dyld cache), 'librocksdb-7.7.dylib' (no such file)\nlibrocksdb-7.dylib: (NativeLoadException) dlopen: dlopen(librocksdb-7.dylib, 0x0002): tried: 'librocksdb-7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibrocksdb-7.dylib' (no such file), '/usr/lib/librocksdb-7.dylib' (no such file, not in dyld cache), 'librocksdb-7.dylib' (no such file)\nlibrocksdb.dylib: (NativeLoadException) dlopen: dlopen(librocksdb.dylib, 0x0002): tried: 'librocksdb.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibrocksdb.dylib' (no such file), '/usr/lib/librocksdb.dylib' (no such file, not in dyld cache), 'librocksdb.dylib' (no such file)\n/opt/homebrew/lib/runtimes/osx-arm64/native/librocksdb-7.7.3.dylib: (NativeLoadException) dlopen: dlopen(/opt/homebrew/lib/runtimes/osx-arm64/native/librocksdb-7.7.3.dylib, 0x0002): tried: '/opt/homebrew/lib/runtimes/osx-arm64/native/librocksdb-7.7.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/runtimes/osx-arm64/native/librocksdb-7.7.3.dylib' (no such file), '/opt/homebrew/lib/runtimes/osx-arm64/native/librocksdb-7.7.3.dylib' (no such file)\n/opt/homebrew/lib/runtimes/osx-arm64/native/librocksdb-7.7.dylib: (NativeLoadException) dlopen: dlopen(/opt/homebrew/lib/runtimes/osx-arm64/native/librocksdb-7.7.dylib, 0x0002): tried: '/opt/homebrew/lib/runtimes/osx-arm64/native/librocksdb-7.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/runtimes/osx-arm64/native/librocksdb-7.7.dylib' (no such file), '/opt/homebrew/lib/runtimes/osx-arm64/native/librocksdb-7.7.dylib' (no such file)\n/opt/homebrew/lib/runtimes/osx-arm64/native/librocksdb-7.dylib: (NativeLoadException) dlopen: dlopen(/opt/homebrew/lib/runtimes/osx-arm64/native/librocksdb-7.dylib, 0x0002): tried: '/opt/homebrew/lib/runtimes/osx-arm64/native/librocksdb-7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/runtimes/osx-arm64/native/librocksdb-7.dylib' (no such file), '/opt/homebrew/lib/runtimes/osx-arm64/native/librocksdb-7.dylib' (no such file)\n/opt/homebrew/lib/runtimes/osx-arm64/native/librocksdb.dylib: (NativeLoadException) dlopen: dlopen(/opt/homebrew/lib/runtimes/osx-arm64/native/librocksdb.dylib, 0x0002): tried: '/opt/homebrew/lib/runtimes/osx-arm64/native/librocksdb.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/runtimes/osx-arm64/native/librocksdb.dylib' (no such file), '/opt/homebrew/lib/runtimes/osx-arm64/native/librocksdb.dylib' (no such file)\n/opt/homebrew/lib/native/arm64/librocksdb-7.7.3.dylib: (NativeLoadException) dlopen: dlopen(/opt/homebrew/lib/native/arm64/librocksdb-7.7.3.dylib, 0x0002): tried: '/opt/homebrew/lib/native/arm64/librocksdb-7.7.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/native/arm64/librocksdb-7.7.3.dylib' (no such file), '/opt/homebrew/lib/native/arm64/librocksdb-7.7.3.dylib' (no such file)\n/opt/homebrew/lib/native/arm64/librocksdb-7.7.dylib: (NativeLoadException) dlopen: dlopen(/opt/homebrew/lib/native/arm64/librocksdb-7.7.dylib, 0x0002): tried: '/opt/homebrew/lib/native/arm64/librocksdb-7.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/native/arm64/librocksdb-7.7.dylib' (no such file), '/opt/homebrew/lib/native/arm64/librocksdb-7.7.dylib' (no such file)\n/opt/homebrew/lib/native/arm64/librocksdb-7.dylib: (NativeLoadException) dlopen: dlopen(/opt/homebrew/lib/native/arm64/librocksdb-7.dylib, 0x0002): tried: '/opt/homebrew/lib/native/arm64/librocksdb-7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/native/arm64/librocksdb-7.dylib' (no such file), '/opt/homebrew/lib/native/arm64/librocksdb-7.dylib' (no such file)\n/opt/homebrew/lib/native/arm64/librocksdb.dylib: (NativeLoadException) dlopen: dlopen(/opt/homebrew/lib/native/arm64/librocksdb.dylib, 0x0002): tried: '/opt/homebrew/lib/native/arm64/librocksdb.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/native/arm64/librocksdb.dylib' (no such file), '/opt/homebrew/lib/native/arm64/librocksdb.dylib' (no such file)\n/opt/homebrew/lib/native/librocksdb-7.7.3.dylib: (NativeLoadException) dlopen: dlopen(/opt/homebrew/lib/native/librocksdb-7.7.3.dylib, 0x0002): tried: '/opt/homebrew/lib/native/librocksdb-7.7.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/native/librocksdb-7.7.3.dylib' (no such file), '/opt/homebrew/lib/native/librocksdb-7.7.3.dylib' (no such file)\n/opt/homebrew/lib/native/librocksdb-7.7.dylib: (NativeLoadException) dlopen: dlopen(/opt/homebrew/lib/native/librocksdb-7.7.dylib, 0x0002): tried: '/opt/homebrew/lib/native/librocksdb-7.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/native/librocksdb-7.7.dylib' (no such file), '/opt/homebrew/lib/native/librocksdb-7.7.dylib' (no such file)\n/opt/homebrew/lib/native/librocksdb-7.dylib: (NativeLoadException) dlopen: dlopen(/opt/homebrew/lib/native/librocksdb-7.dylib, 0x0002): tried: '/opt/homebrew/lib/native/librocksdb-7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/native/librocksdb-7.dylib' (no such file), '/opt/homebrew/lib/native/librocksdb-7.dylib' (no such file)\n/opt/homebrew/lib/native/librocksdb.dylib: (NativeLoadException) dlopen: dlopen(/opt/homebrew/lib/native/librocksdb.dylib, 0x0002): tried: '/opt/homebrew/lib/native/librocksdb.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/native/librocksdb.dylib' (no such file), '/opt/homebrew/lib/native/librocksdb.dylib' (no such file)\n/opt/homebrew/lib/arm64/librocksdb-7.7.3.dylib: (NativeLoadException) dlopen: dlopen(/opt/homebrew/lib/arm64/librocksdb-7.7.3.dylib, 0x0002): tried: '/opt/homebrew/lib/arm64/librocksdb-7.7.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/arm64/librocksdb-7.7.3.dylib' (no such file), '/opt/homebrew/lib/arm64/librocksdb-7.7.3.dylib' (no such file)\n/opt/homebrew/lib/arm64/librocksdb-7.7.dylib: (NativeLoadException) dlopen: dlopen(/opt/homebrew/lib/arm64/librocksdb-7.7.dylib, 0x0002): tried: '/opt/homebrew/lib/arm64/librocksdb-7.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/arm64/librocksdb-7.7.dylib' (no such file), '/opt/homebrew/lib/arm64/librocksdb-7.7.dylib' (no such file)\n/opt/homebrew/lib/arm64/librocksdb-7.dylib: (NativeLoadException) dlopen: dlopen(/opt/homebrew/lib/arm64/librocksdb-7.dylib, 0x0002): tried: '/opt/homebrew/lib/arm64/librocksdb-7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/arm64/librocksdb-7.dylib' (no such file), '/opt/homebrew/lib/arm64/librocksdb-7.dylib' (no such file)\n/opt/homebrew/lib/arm64/librocksdb.dylib: (NativeLoadException) dlopen: dlopen(/opt/homebrew/lib/arm64/librocksdb.dylib, 0x0002): tried: '/opt/homebrew/lib/arm64/librocksdb.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/arm64/librocksdb.dylib' (no such file), '/opt/homebrew/lib/arm64/librocksdb.dylib' (no such file)\n/opt/homebrew/lib/librocksdb-7.7.3.dylib: (NativeLoadException) dlopen: dlopen(/opt/homebrew/lib/librocksdb-7.7.3.dylib, 0x0002): tried: '/opt/homebrew/lib/librocksdb-7.7.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/librocksdb-7.7.3.dylib' (no such file), '/opt/homebrew/lib/librocksdb-7.7.3.dylib' (no such file)\n/opt/homebrew/lib/librocksdb-7.7.dylib: (NativeLoadException) dlopen: dlopen(/opt/homebrew/lib/librocksdb-7.7.dylib, 0x0002): tried: '/opt/homebrew/lib/librocksdb-7.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/librocksdb-7.7.dylib' (no such file), '/opt/homebrew/lib/librocksdb-7.7.dylib' (no such file)\n/opt/homebrew/lib/librocksdb-7.dylib: (NativeLoadException) dlopen: dlopen(/opt/homebrew/lib/librocksdb-7.dylib, 0x0002): tried: '/opt/homebrew/lib/librocksdb-7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/librocksdb-7.dylib' (no such file), '/opt/homebrew/lib/librocksdb-7.dylib' (no such file)\n/opt/homebrew/lib/librocksdb.dylib: (NativeLoadException) dlopen: dlopen(/opt/homebrew/lib/librocksdb.dylib, 0x0002): tried: '/opt/homebrew/lib/librocksdb.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/librocksdb.dylib' (no such file), '/opt/homebrew/lib/librocksdb.dylib' (no such file)\nlibrocksdb-7.7.3.dylib: (NativeLoadException) dlopen: dlopen(librocksdb-7.7.3.dylib, 0x0002): tried: 'librocksdb-7.7.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibrocksdb-7.7.3.dylib' (no such file), '/usr/lib/librocksdb-7.7.3.dylib' (no such file, not in dyld cache), 'librocksdb-7.7.3.dylib' (no such file)\nlibrocksdb-7.7.dylib: (NativeLoadException) dlopen: dlopen(librocksdb-7.7.dylib, 0x0002): tried: 'librocksdb-7.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibrocksdb-7.7.dylib' (no such file), '/usr/lib/librocksdb-7.7.dylib' (no such file, not in dyld cache), 'librocksdb-7.7.dylib' (no such file)\nlibrocksdb-7.dylib: (NativeLoadException) dlopen: dlopen(librocksdb-7.dylib, 0x0002): tried: 'librocksdb-7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibrocksdb-7.dylib' (no such file), '/usr/lib/librocksdb-7.dylib' (no such file, not in dyld cache), 'librocksdb-7.dylib' (no such file)\nlibrocksdb.dylib: (NativeLoadException) dlopen: dlopen(librocksdb.dylib, 0x0002): tried: 'librocksdb.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibrocksdb.dylib' (no such file), '/usr/lib/librocksdb.dylib' (no such file, not in dyld cache), 'librocksdb.dylib' (no such file)"
at at NativeImport.Importers.Import[T](INativeLibImporter importer, String libName, String version, Boolean suppressUnload)\n at NativeImport.Auto.Import[T](String name, String version, Boolean suppressUnload)\n at RocksDbSharp.Native..cctor()
--- End of inner exception stack trace ---
at RocksDbSharp.OptionsHandle..ctor()\n at RocksDbSharp.Options`1..ctor()\n at RocksDbSharp.DbOptions..ctor()\n at Ferrite.Data.Repositories.RocksDBContext..ctor(String path) in /Users/mqh/Desktop/Git/Ferrite/Ferrite.Data/Repositories/RocksDBContext.cs:line 35\n at Ferrite.Data.Repositories.LocalUnitOfWork..ctor() in /Users/mqh/Desktop/Git/Ferrite/Ferrite.Data/Repositories/LocalUnitOfWork.cs:27

**Comment by theolivenbaum** [comment]
Are you running .net on Rosetta or on ARM ?
If the second, then you'll need to grab a copy manually of RockDB built for ARM from their repository

**Comment by mailes** [comment]
> Are you running .net on Rosetta or on ARM ?
> If the second, then you'll need to grab a copy manually of RockDB built for ARM from their repository

There is no relevant dynamic library generated in osx-arm64, so there is no problem in osx-x64.


![WX20221208-143450@2x](https://user-images.githubusercontent.com/2554806/206375889-03bedb42-51ef-488d-9da9-4eb466a30dce.png)
![WX20221208-143502@2x](https://user-images.githubusercontent.com/2554806/206375901-f29b36f6-6ca9-4a73-b49c-699e29703eb2.png)

**Comment by theolivenbaum** [comment]
Closed in #15
