### ISSUE TITLE
Release 7.9.2

### ISSUE THREAD

**Issue by flcl42** [curiosity-ai/rocksdb-sharp#40]
7.7.3 -> 7.9.2 contains a lot of bug fixes including memory leaks related ones. Several users reported memory consumption issues. We want to test the new version, could you build the new one? Thanks in advance!

**Comment by hakbl54** [comment]
Is there any plan to build the new version?

**Comment by theolivenbaum** [comment]
Hi @hakbl54 @flcl42, there's an issue in the build since a few versions, I'll see if I can fix it asap!

**Comment by theolivenbaum** [comment]
Just released 8.0.0 if you want to try: https://www.nuget.org/packages/RocksDB/8.0.0.37400
