### ISSUE TITLE
Dependency issues/differences on macOS x64

### ISSUE THREAD

**Issue by rubo** [curiosity-ai/rocksdb-sharp#45]
There's a difference between the dependencies of the `osx-x64/native/librocksdb.dylib` from NuGet package and the official `librocksdbjni-osx-x86_64.jnilib` from the Maven repo. Why's that?

Dependencies for `librocksdbjni-osx-x86_64.jnilib`:

- `/usr/lib/libc++.1.dylib`
- `/usr/lib/libSystem.B.dylib`

Dependencies for `librocksdb.dylib`:

- `@loader_path/libsnappy.dylib`
- `@loader_path/libz.dylib`
- `/usr/lib/libbz2.1.0.dylib`
- `@loader_path/liblz4.dylib`
- `@loader_path/libzstd.dylib`
- `/usr/lib/libc++.1.dylib`
- `/usr/lib/libSystem.B.dylib`

Furthermore, we have all sorts of issues with the v8.0.0.37452 because of bzip2 dependency. Updating to v8.0.0.37755 fixes the issue, but even with the latest v8.3 there's a difference as shown above. I wondering why. Is it a custom build?

**Comment by theolivenbaum** [comment]
Hi @rubo, indeed there are 2 builds: For macOS ARM, I'm using the official build from RocksDB published to Maven, while for macOS Intel we have a [build script](https://github.com/curiosity-ai/rocksdb-sharp/blob/master/build-native/build-rocksdb.sh). I didn't want to change the macOS Intel library when I added macOS ARM to the package, as I wasn't sure if the Maven dependencies difference would be a problem.

**Comment by rubo** [comment]
As I mentioned, the problem is with custom build dependencies not the official ones. I'd prefer having official builds for both Linux x64 and macOS x64. Otherwise, we're considering branching and running our own package just because of this.
