### ISSUE TITLE
Question : CancelAllBackgroundWork

### ISSUE THREAD

**Issue by gm0124816** [curiosity-ai/rocksdb-sharp#50]
Hi,

Nice work so far, love the speed of Rocksdb from within C# ! Just one question. I did not find a "Close" method and for sure no "CancelAllBackgroundWork" method.

Are these handled automatically in the background ?

Cheers,
Geert

**Comment by theolivenbaum** [comment]
Hi @gm0124816 

To close the DB, just call Dispose() on it:

`````csharp
var db = RocksDB.Open(...);
// your code
db.Dispose(); //Cancels all background work and closes the database
`````
