### ISSUE TITLE
Keeping support for net 2.0

### ISSUE THREAD

**Issue by zhentouk** [curiosity-ai/rocksdb-sharp#6]
Since a few releases, the support for net 2.0 (and 4.0) was dropped, in favour of net 2.1 (and 5.0).
And this wouldn't be a problem, but the Unity game engine doesn't support net 2.1.
It would be great, if you could keep net 2.0 support using #if #endif directives, so ppl like me can use it for Unity aswell.

**Comment by MohammedLarabi** [comment]
Same issue here. .NET Framework does not support .NET Standard 2.1.
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by theolivenbaum** [comment]
Hi @zhentouk  @MohammedLarabi - you can keep using this version if you want netstandard2.0 support: https://www.nuget.org/packages/rocksdb/6.15.2.14869

I'll add to our backlog to see if we re-add support for netstandard2.0 - always annoying that Unity is still stuck in the past :(
